version: '3.8'
services:

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    env_file:
      - kafka.env
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  consumer:
    container_name: consumer
    build:
      context: consumer
    environment:
      kafkaURL: kafka:9092
      topic: orbit
      GroupID: logger-group
    depends_on:
      - kafka

  producer:
    container_name: producer
    build:
      context: producer
    environment:
      kafkaURL: kafka:9092
      topic: orbit
    depends_on:
      - kafka
